name: Lines of Code

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday
  workflow_dispatch:  # Allows manual execution

jobs:
  count-loc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Count Lines of Code
        uses: marketplace/actions/lines-of-code@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update README.md
        run: |
          echo "### Total Lines of Code in My GitHub Repositories 🚀" > loc.md
          cat loc.md README.md > newREADME.md && mv newREADME.md README.md
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Updated LOC in README.md" || echo "No changes to commit"
          git push
